name: Issue triage
on:
  issues:
    types: [edited, opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps: 
      - name: Label issue
  
        run: |
          if (contains(github.event.issue.body, 'bug')) {
            echo '::add-labels: bug';
          } else if (contains(github.event.issue.body, 'feature')) {
            echo '::add-labels: feature';
          } else {
            echo 'Labelling issue as needs-triage';
            echo '::add-labels: needs-triage';
          }
