name: Using matrix strategy to run multiple configurations
on:
  push:
    branches:
      main

jobs:
  job_1:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os_version: [macos-latest, ubuntu-latest]
        node_version: [14, 16, 18]
  
    name: First job
    runs-on: "${{ matrix.os_version }}"
    steps: 
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: "${{ matrix.node_version }}"
