name: My first workflow

on:
  push:
    branches:
      - main
      
  workflow_dispatch:
    inputs:
      homedrive:
        description: 'The home drive on the machine'
        required: true
      logLevel:
        description: 'Log level'
        default: 'info'
        type: choice
        options: [info, warning, debug]
      tag:
        description: 'Apply tag after successfull test run'
        required: true
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    
    steps:
      - run: |
          echo "Homedrive: ${{ inputs.homedrive }}"
          echo "Log level: ${{ inputs.logLevel }}"
          echo "Tag source: ${{ inputs.tag }}"
        name: Workflow Inputs  
        if: ${{ github.event_name == 'workflow_dispatch' }}

  PrintingJob:
    runs-on: ubuntu-latest
    needs: MyFirstJob
    steps:
      - run: "echo Job: ${{ github.job }}"

  OtherJob:
    runs-on: ubuntu-latest
    needs: MyFirstJob
    steps:
      - run: "echo Job: ${{ github.job }}"

  LastJob:
    runs-on: ubuntu-latest
    needs: [PrintingJob, OtherJob]
    steps:
      - run: "echo Job: ${{ github.job }}"
