name: My first workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hi my brethern!"

      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
