on: push

jobs:
  generate_secret_output:
    runs-on: ubuntu-latest
    
    steps:
      - id: sets-secret
        name: Generate, mask and output a secret
        run: |
          big_secret=$((RANDOM))
          echo "::add-mask::$big_secret"
          echo "secret-number=$big_secret" >> "$GITHUB_OUTPUT"
          
      - name: Use that secret output (protected by a mask)
        run: |
          echo "the secret number is ${{ steps.sets-secret.outputs.secret-number }}
