on: push

jobs:
  working_with_env:
    runs-on: ubuntu-latest

    steps:
      - name: Set value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV

      - run: |
          echo "${{ env.action_state }}" # This will output 'yellow'
          
          echo "Hi people! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "I like this feature. :medal_sports:" >> $GITHUB_STEP_SUMMARY
          echo "<h2>Nice to see you again</h2>" >> $GITHUB_STEP_SUMMARY
